### ISSUE TITLE
Firefox connecting Bitcoin and signing Bitcoin transactions broken

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5285] opened 2024-04-22 09:21 UTC
Trying to connect on luminex.io leads to "leather not found" message
Trying to connect on gamma.io sends you to the firefox store... a hijacked link (hiro wallet) @nicksainato
Trying to connect bitcoin on app.alexlab.co sends you to leather.io

When already connected with a prior version of the firefox extension, a user reported issues while trying to go through the steps to mint here https://luminex.io/runes/mint
![image](https://github.com/leather-wallet/extension/assets/33360391/20ea09a5-1435-49f3-808b-66c2cd7e38f4)

On stacks.gamma.io I can connect to stacks. On app.alexlab.co I can't connect the leather network either. Does Firefox work with the new LeatherProvider object?

**Comment by pete-watters** [comment] 2024-06-28 09:57
@314159265359879 I took a look into this and I could connect on `luminex.io` without any problem. 

I saw the same issue as you when trying to connect to `gamma.io` + `app.alexlab.co` but I think this is caused by the fact that we don't officially support Firefox anymore so wallet authentication will not work in some cases. 

Curious on your thoughts here @markmhendrickson @kyranjamie

**Comment by kyranjamie** [comment] 2024-06-28 12:24
We don't support Firefox, and I believe this should be closed as wontfix.

**Closed as completed** 2024-06-28 13:52 UTC
Labels: bug, bug-p2, area:firefox
