### ISSUE TITLE
Add fee estimation caps to the config file

### ISSUE THREAD

**Issue by andresgalante** [blockstack/blockstack-app#2039] opened 2021-12-06 14:48 UTC
At the moment fees are being capped. 

By adding a toggle to the config file we'd have an easy way to add or remove those caps without having to go through a wallet release.

**Comment by Eshwari007** [comment] 2022-01-03 21:03
@beguene Appreciate some testing input or use case for the ticket
Thx

**Comment by beguene** [comment] 2022-01-05 10:49
@Eshwari007 This is a bit tricky to test. I added a console.log so you can check.
The data looks like this if you open the devtools in google chrome when you are on the send page
<img width="707" alt="fee-estimations-config" src="https://user-images.githubusercontent.com/1501454/148202923-d8382d6b-0900-4cd6-b370-6c0498b40585.png">
The default values for fee estimations caps are
"maxValues": [500000, 750000, 2000000]


# How to change the default values
To change the values in the config you can change it in this current branch:
feat/use-wallet-config-for-max-fee-estimations/I2039
you can change the values directly here
https://github.com/hirosystems/stacks-wallet-web/blob/feat/max-fee-estimation-qa-config/I2039/config/wallet-config.json
Those changes have to be committed to the branch to take effect.

Here are some test cases:

# Test case 1 : no regression
Just test that everything works correctly



# Test case 2: change the max values
1. Change wallet-config.json     "maxValues": to something else for example [800000, 900000, 4000000)
2. Login and go to send page
3. Check that the values in the chrome console are the one you set.
4. Fill the form to send and check that the fees are capped according to the values you set

# Test case 3: disable max values
1. change wallet-config.json maxValuesEnabled to false
2. Login and go to send page
3. It should still work.
4. Check that the values in the chrome console are the default values (500000, 750000, 2000000)

**Comment by Eshwari007** [comment] 2022-01-06 19:36
@beguene I am trying to view the console log but seems the connection issue with url:http://localhost:8000/config/wallet-config.json
<img width="1327" alt="Screen Shot 2022-01-06 at 2 34 52 PM" src="https://user-images.githubusercontent.com/38872890/148440806-da22e409-1d88-4491-98f7-c0723fd62008.png">

**Comment by beguene** [comment] 2022-01-07 08:07
@Eshwari007 My bad, I forgot to remove changes to test locally. It's working now.

**Comment by Eshwari007** [comment] 2022-01-07 18:04
Thank you @beguene 
Was able to test the fee estimation -thx to the console log.

**Closed as completed** 2022-02-01 08:27 UTC
Labels: effort:medium
