### ISSUE TITLE
Support API for changing the wallet's network entirely. 

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4193] opened 2023-09-07 21:17 UTC
Something like this:

![Untitled](https://github.com/leather-wallet/extension/assets/33360391/1ed5729e-a0ca-4390-9735-85cbb3d6c421)

**Comment by kyranjamie** [comment] 2023-09-11 07:01
Dupe of #4027, #1281

**Closed as completed** 2023-09-14 16:30 UTC
Labels: enhancement-p1, area:networks
