### ISSUE TITLE
Unable to log in-Invalid password-Argentina

### ISSUE THREAD

**Issue by Criptid-I** [blockstack/blockstack-app#2094] opened 2021-12-19 22:11 UTC
Hi, everyone, 
I hope you can help me. I´m unable to log into my Hiro wallet. When I introduce the password, I get a message saying it´s an incorrect password. I have tried several times, and I´m sure it´s the right one, I even sent it to a friend (who lives in the US), along with the seed phrase, and he was able to log in. I tried reinstalling the Hiro wallet several times and opening it with different Google accounts, with Brave and Firefox, and even using a different computer but nothing worked. Finally, I decided to get a new wallet and asked my friend to send the contents of the old wallet to my new one. Unfortunatelly, when I tried to open my new wallet (with a different password), I ran into the same issue. I´ve heard someone else living in Argentina had the same problem. Is there anything you could do to help me?
Thanks in advance for your time and help!
Best, 
Laura

**Comment by Usergithub99** [comment] 2021-12-24 06:12
Hola! Solucionaste?

**Comment by andresgalante** [comment] 2022-01-11 13:46
Hi Laura, I am in Argentina and I can't reproduce the issue. Do you still have it? else I'll close this issue

**Closed as completed** 2022-01-12 16:27 UTC
Labels: bug, area:password
