### ISSUE TITLE
Ordinal inscription history when BTC is send, why? Ordinal appears in pending state while the address it resides on has no pending history

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4762] opened 2023-12-30 23:20 UTC
![image](https://github.com/leather-wallet/extension/assets/33360391/651fae35-3575-4db6-ae4e-483bf032611f)

Clicking that in the wallet takes the user to this inscription on the explorer. But the amount displayed is associated with this transaction (a normal BTC transfer)
https://mempool.space/tx/578a479636d6f73635c33ee87d8617d61f67a8eabdb5447990a3de671e5bcaa7
(That amount displayed (-0.00132191) is the fee and the first output of this transaction together)

https://ordinals.hiro.so/inscription/d674b54088a3a4f623a1f06ea02ef8590e4f95b5742314f0c1ceae56d27b12d3i0
![image](https://github.com/leather-wallet/extension/assets/33360391/24d45b2e-1677-41fc-a7d7-6a53ca96a0be)

it is on this address according to ordinals.hiro.so
https://mempool.space/address/bc1pg6fhzfl97zqr92sdp4tey0je2sgarqnd00ng54cyuc9y72r5gs7s548rkg

Which shows no pending transactions
![image](https://github.com/leather-wallet/extension/assets/33360391/593b5f9c-12e3-4298-9dbc-cfb1d9b04a52)

**Comment by 314159265359879** [comment] 2023-12-30 23:26
https://ordinals.com/output/578a479636d6f73635c33ee87d8617d61f67a8eabdb5447990a3de671e5bcaa7:1
https://ordinals.com/output/578a479636d6f73635c33ee87d8617d61f67a8eabdb5447990a3de671e5bcaa7:0

Not sure if these are expected to show inscriptions when they're not confirmed yet... none are displayed for these outputs. And there is no taproot address in the inputs or outputs either.

**Comment by 314159265359879** [comment] 2024-01-02 14:09
The user confirmed no ordinals were transferred, after the transaction was mined
![image](https://github.com/leather-wallet/extension/assets/33360391/b77f2633-f3a4-4554-8dba-001690b8d50a)

**Comment by markmhendrickson** [comment] 2024-01-02 17:01
Dupe of https://github.com/leather-wallet/extension/issues/4688?

**Comment by 314159265359879** [comment] 2024-01-02 18:43
Yes it is a dupe, I actually thought that had a taproot input or output but it does not. I will close this in favor of 4688.

**Closed as completed** 2024-01-02 18:45 UTC
Labels: bug, area:ordinals
