### ISSUE TITLE
Prevent accidental BTC retrieval from taproot: halt showing uninscribed BTC when there are pending incoming transactions to a taproot address

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4512] opened 2023-11-13 16:09 UTC
We show this, and a warning and advice to check every UTXO to make sure there are no inscribed sats with them before retrieving.
![image](https://github.com/leather-wallet/extension/assets/33360391/ef2328db-c3ee-4bd2-99a7-f888f7d3f935)

Sometimes these are ignored/missed and users still retrieve UTXO's with inscriptions to their bitcoin address. This enhancement can help prevent that by not showing uninscribed BTC until all pending transactions to the taproot address (likely ordinal deposits) are handled. 

When transactions are not confirmed the UTXO's can falsely show as uninscribed.

**Comment by kyranjamie** [comment] 2024-01-25 19:18
Dupe of #4513

**Closed as completed by kyranjamie** 2024-01-25 19:18 UTC
Labels: enhancement-p3, area:bitcoin, area:ordinals, enhancement, area:asset-migrations
