### ISSUE TITLE
Unable to use Leather swap feature for STX to WELSH

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#5022] opened 2024-03-05 01:52 UTC
An issue is preventing swapping STX to Welsh using Leather swap feature, while other swaps seem to work fine.

<img width="574" alt="LeatherSwap" src="https://github.com/leather-wallet/extension/assets/132958967/a07906ad-723f-4e56-a2a3-33ab732a5aba">

<img width="933" alt="swapconsole" src="https://github.com/leather-wallet/extension/assets/132958967/05170dc1-f13b-4830-88ae-91c432062a62">

**Comment by 314159265359879** [comment] 2024-03-05 08:45
Workaround for now is that users can use https://app.alexlab.co to create the swap instead.

**Comment by markmhendrickson** [comment] 2024-03-08 17:16
@DeeList any error shown in the console here?

**Comment by 314159265359879** [comment] 2024-03-08 21:17
I noticed that Welsh <-> ALEX does work. 

For some reason, the routed swaps do not work. The swap is expected to route it for the user STX to ALEX first and then ALEX to Welsh because that is how tokens are paired in liquidity pools. 

Is this something can be fixed on our end or is this something on the end of the swapprovider?

This issue is reproducible. 
Try STX to Welsh or Welsh to STX and it doesn't calculate an amount. 
Try ALEX to Welsh or the other way around and it does.

**Comment by DeeList** [comment] 2024-03-08 23:41
> @DeeList any error shown in the console here?

@markmhendrickson Yes, added screenshot.

<img width="933" alt="swapconsole" src="https://github.com/leather-wallet/extension/assets/132958967/386fcae7-406a-45fd-b968-f19d7ba9c97d">

**Comment by 314159265359879** [comment] 2024-03-09 12:16
This is from Kyle

>We have found the issue and published a new version of our SDK. 
>
>v0.1.26 
>
>https://github.com/alexgo-io/alex-sdk/commit/b350caae7154618242b85cd47519a72fcf041e2b
>
>Please help upgrade to the latest sdk version.

**Closed as completed** 2024-03-20 13:53 UTC
Labels: bug, bug-p3, area:swaps
