### ISSUE TITLE
Ledger "unexpected application error!" after clicking the account to connect with "No LedgerRequestKeysContext found"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4786] opened 2024-01-09 10:33 UTC
Reproduce with these steps 
1. Sign out wallet
2. Connect wallet to Stacks with Ledger, so account balance shows in the extension
3. Then disconnect the ledger device from computer
4. Sign in to a dapp for example lockstacks.com
5. Select account to connect with
6. See error:

![image](https://github.com/leather-wallet/extension/assets/33360391/88b68499-59d6-444d-b31c-ba6deaaf2029)

To fix issue: connect Ledger Device to your computer again, start the Stacks app on the Ledger device then try again. 

I think instead of this error the wallet should show better guidance for the user.

**Comment by wizard1786** [comment] 2024-01-17 03:11
How about for edge browser?

**Comment by wizard1786** [comment] 2024-01-17 03:15
Did not work with edge browser got the same error message 
Any help on transferring stx out of leather wallet ?

**Comment by edgarkhanzadian** [comment] 2024-01-24 10:11
@314159265359879 I've tried reproducing the error but i didn't get any result. What version did you get this error on? Can you, please, try reproducing it on the dev branch now?

Note: you won't be able to see it in the video, but i disconnected the ledger device right after signing in into leather with stacks app.

https://github.com/leather-wallet/extension/assets/22010816/74ceb7b4-9449-4ce7-85a8-98f6d9f82f22

**Comment by wizard1786** [comment] 2024-01-24 14:34
???? Dev branch Sent from my iPhoneOn Jan 24, 2024, at 5:12 AM, Edgar Khanzadian ***@***.***> wrote:﻿
@314159265359879 I've tried reproducing the error but i didn't get any result. What version did you get this error on? Can you, please, try reproducing it on the dev branch now?
Note: you won't be able to see it in the video, but i disconnected the ledger device right after signing in into leather with stacks app.
https://github.com/leather-wallet/extension/assets/22010816/74ceb7b4-9449-4ce7-85a8-98f6d9f82f22

**Comment by wizard1786** [comment] 2024-01-24 15:35
I give up If I used a different ledger device would that make a difference? Sent from my iPhoneOn Jan 24, 2024, at 5:12 AM, Edgar Khanzadian ***@***.***> wrote:﻿
@314159265359879 I've tried reproducing the error but i didn't get any result. What version did you get this error on? Can you, please, try reproducing it on the dev branch now?
Note: you won't be able to see it in the video, but i disconnected the ledger device right after signing in into leather with stacks app.
https://github.com/leather-wallet/extension/assets/22010816/74ceb7b4-9449-4ce7-85a8-98f6d9f82f22

**Comment by edgarkhanzadian** [comment] 2024-01-25 09:18
@wizard1786 using a different ledger device shouldn't make a difference in theory, but let me know if you are able to reproduce it on another type of device. I was unable to repro it on ledger nano X

**Comment by 314159265359879** [comment] 2024-01-25 14:41
@edgarkhanzadian I first tested this with version 6.22.0 of the wallet and a Nano S plus, it is still the same for me today with version 6.24.0. 
Testing on Chrome version 120.0.6099.227
firmware version 1.1.1

You're video isn't playing for me (looks like an issue with github). 

https://github.com/leather-wallet/extension/assets/33360391/bc4c87b4-c159-491d-b630-401a463c7143

**Comment by wizard1786** [comment] 2024-01-25 15:15
Nothing seems to make a difference Sent from my iPhoneOn Jan 25, 2024, at 9:42 AM, Werner ***@***.***> wrote:﻿
@edgarkhanzadian I first tested this with version 6.22.0 of the wallet and a Nano S plus, it is still the same for me today with version 6.24.0.
Testing on Chrome version 120.0.6099.227
firmware version 1.1.1
You're video isn't playing for me (looks like an issue with github).
https://github.com/leather-wallet/extension/assets/33360391/bc4c87b4-c159-491d-b630-401a463c7143

**Comment by wizard1786** [comment] 2024-01-25 17:03
Tried to send an mp4 file of video , says it is too large ? how to get it to you 

Connected to a different stacks website got the same error message

**Comment by 314159265359879** [comment] 2024-01-25 23:28
@wizard1786 We have enough video material, thanks for the effort though. 

If you keep hitting this error even when the Ledger device is connected to your computer and it is the same device used to setup your Leather wallet. I assume there is an issue with connection or cable. Try it on another device, another browser and/or with another cable to exclude any issues with those. 

Before signing in on a dapp, make sure your Leather wallet is on the same account you want to sign in with. Then sign in on the page. Please connect via support@leather.io for further assistance if you see this persist.

**Comment by kyranjamie** [comment] 2024-03-24 17:29
Reopening this issue, saw it happen.

When trying to sign a transaction with Ledger, and the device isn't able to connect, we route to an error page (that isn't within the context so we see this error).

**Comment by wizard1786** [comment] 2024-03-24 17:53
Huh ???

**Comment by pete-watters** [comment] 2024-05-09 13:37
I've been investigating this but as yet unable to reproduce. Once signed in to a DAPP with ledger, if I then disconnect, when I try and perform an action it prompts me to connect the Ledger again.


 - I signed in to Gamma 
 - initiated a purchase of a BTC collectible 
 - disconnected the ledger
 - observed that the popup prompts me to connect my Ledger and doesn't error
 
 I'll keep investigating and try with a Stacks interaction instead in case there is some bug there. 
 
 @kyranjamie do you remember exactly what you were doing to cause the error? Maybe its different than the device not being connected and it's an issue with communicating with a connected device?

**Comment by kyranjamie** [comment] 2024-05-09 13:46
This was a routing issue I think, where you get routed somewhere outside the context. Try with lockstacks.com

**Comment by pete-watters** [comment] 2024-05-10 05:48
I could be missing something here but if my Ledger is not connected, I consistently get a prompt to ask me to connect it rather than hitting any kind of uncaught error. 

`No LedgerRequestKeysContext found ` is an error we throw in `useLedgerRequestKeysContext` and I cannot find any instances of it in Sentry, albeit it for the past 90 days. 

If I try with `lockstacks.com` to:
- connect my wallet - with a disconnected Ledger
https://github.com/leather-wallet/extension/assets/2938440/69f1e9c7-d66b-4c1e-a8f5-5d0d0d56049e

- join a staking pool - with a disconnected Ledger 
https://github.com/leather-wallet/extension/assets/2938440/a6cf0bb3-163d-430a-a24c-62ea8e2d9f2c

In both cases, the Leather popup handles the lack of Ledger connection gracefully and shows the `We're unable to connect to your Ledger device` warning. 

Looking at the code and two places where we use `useLedgerRequestKeysContext` and could potentially hit this error are in: 
- ConnectLedgerRequestKeys
- AddMoreKeysLayout 

If I am testing `ConnectLedgerRequestKeys` AKA the initial Route - ConnectLedger - `connect-your-ledger` it seems to be handled well. 

If it is still a bug it seems likely related to `AddMoreKeysLayout` but when I look deeper into that, it seems like dead code no longer used. In our code we only have:
-  a reference to only the route `RouteUrls.LedgerAddMoreKeys` in `route-urls`
- Handling of that route in `ledgerRequestKeysRoutes` with component `AddMoreKeysLayout` 

@kyranjamie : do you know what the `LedgerAddMoreKeys` route is for? Does it relate to https://github.com/leather-wallet/extension/issues/2502? It was added in this PR - https://github.com/leather-wallet/extension/pull/4042/ 

@314159265359879 : I can't play your repro video linked in https://github.com/leather-wallet/extension/issues/4786#issuecomment-1910347981. When you have time can you please help me try and reproduce this?

**Comment by kyranjamie** [comment] 2024-05-10 08:30
Thanks for the investigation @pete-watters. Could be that it's been fixed 👍🏼 

RE: `RouteUrls.LedgerAddMoreKey`. At one point, we had a route that would allow you to add more keys, after you'd added the first, but I think this has been removed as we show the connect button on homepage. As such, think we can remove it.

**Comment by pete-watters** [comment] 2024-05-10 09:02
OK thanks. I will remove that route and when Werner is back I will double check with him and if he cannot reproduce I will close.

**Closed as completed** 2024-05-10 12:46 UTC
Labels: bug, bug-p2, effort:medium, area:ledger

**Comment by pete-watters** [comment] 2024-05-13 10:23
@314159265359879 when you have a chance can you please help test if this is still a problem? I was unable to reproduce so I think it is fixed but if you can still reproduce it please let me know

**Comment by 314159265359879** [comment] 2024-05-13 12:25
@pete-watters I retested this too, and it looks resolved indeed. It is handled gracefully now.

**Comment by pete-watters** [comment] 2024-05-13 14:45
OK that's great, thanks for confirming 👍
