### ISSUE TITLE
Fix vertical offset of dismissal option for hardware device connection view

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5734] opened 2024-08-07 10:35 UTC
https://github.com/user-attachments/assets/e518b59e-869f-46cb-9825-a19b1ea46aa2

**Comment by markmhendrickson** [comment] 2024-08-07 10:38
Also seen in this state:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/1afcec19-52aa-4bd0-9505-118c7e05072b">

**Comment by pete-watters** [comment] 2024-08-20 06:10
I took a look at this as I will update the UI library anyway and it is quick to solve but adding good value. The problem is not having a minimum header height in dialog headers when there is no title. 

I just want to double check that the other dialog headers with title have the correct height. 

An example of this is `Sign out` which looks like this:
![Screenshot 2024-08-20 at 07 08 20](https://github.com/user-attachments/assets/46b79c5f-3a99-4d01-81ae-796e01dd7caa)

I can change it to have the same height as the non-title ones or else handle those on a specific case basis. If change them all it will look like this on dialogs with title (slightly taller) :
![Screenshot 2024-08-20 at 07 09 08](https://github.com/user-attachments/assets/713d10f6-be36-461c-9a9d-1174f7fc3bb0)

Here is a video that shows it more clearly: 

https://github.com/user-attachments/assets/5a07e503-4110-4b6b-b4d5-a6efe6c392cc

Let me know what you think @fabric-8 @markmhendrickson @mica000

**Comment by pete-watters** [comment] 2024-08-21 04:41
@fabric-8 confirmed it's OK here: https://trustmachines.slack.com/archives/C05LRS7G44R/p1724170032342449?thread_ts=1724166569.243219&cid=C05LRS7G44R

> after checking and from what I can see headers are supposed to have a unit-height of 8.5 (68px) — So yes, I think you could apply that same logic to title-less headers with (ie header with just a close button)

**Comment by pete-watters** [comment] 2024-08-21 13:00
I merged a fix to the mono repo UI library. Next I need to update this in the extension

**Comment by pete-watters** [comment] 2024-08-21 14:24
Extension integration PR open [here](https://github.com/leather-io/extension/pull/5796)

**Closed as completed** 2024-08-21 15:34 UTC
Labels: area:ledger, needs:visual-improvement

**Comment by markmhendrickson** [comment] 2024-08-21 16:24
Should we add a (screenshot-based) integration test for this fix?

**Comment by pete-watters** [comment] 2024-08-22 04:59
> Should we add a (screenshot-based) integration test for this fix?

We should. I will investigate screenshot based testing in here https://github.com/leather-io/issues/issues/264 and include this
