### ISSUE TITLE
Fix display of locked vs. unlocked STX balances

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4552] opened 2023-11-21 12:25 UTC
They appear to have regressed, perhaps due to UI library work:

![image](https://github.com/leather-wallet/extension/assets/28991/64215ac5-1a01-4210-9916-d21ed5a25c21)

**Comment by pete-watters** [comment] 2023-11-21 13:32
This was broken before style updates but I will fix it 👍

**Comment by kyranjamie** [comment] 2024-01-24 18:46
Closing as dupe of https://github.com/leather-wallet/extension/issues/4851

**Closed as completed by kyranjamie** 2024-01-24 18:46 UTC
Labels: area:stacks, needs:visual-improvement
