### ISSUE TITLE
Design system - Select dropdown component

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4301] opened 2023-10-02 14:46 UTC
Create a generic Leather-themed Radix dropdown component, where each slot component is exported from `@app/componet/dropdown`.

**Comment by mica000** [comment] 2023-10-03 11:42
@fbwoolf These are the base to the selector component
https://www.figma.com/file/2MLHeIeL6XPVi3Tc2DfFCr/%E2%9D%96-Leather-%E2%80%93-Design-System?type=design&node-id=2081-3746&mode=design


![Image](https://github.com/leather-wallet/extension/assets/119523541/66f7d5fd-571d-490f-94c7-eb274ed3f493)


![Image](https://github.com/leather-wallet/extension/assets/119523541/04a7e48d-0a1a-4637-a172-54399cd624f9)

**Comment by fbwoolf** [comment] 2023-10-03 13:12
@markmhendrickson in Radix, a dropdown and a select component are two different things. The issue and location should be renamed to match the designs for a `Select` component?

**Comment by markmhendrickson** [comment] 2023-10-03 15:55
@mica000 might be best to answer

**Comment by mica000** [comment] 2023-10-03 16:37
Yes, makes sense to rename to selector

**Comment by fbwoolf** [comment] 2023-10-03 17:26
> Yes, makes sense to rename to selector

@mica000 is the interactions that it drops down below the trigger, or does it popup over what is selected? Ref the playground to see the difference here. I need to know what we want bc they are two different Radix components to start from. cc @kyranjamie 

https://www.radix-ui.com/themes/playground#select
https://www.radix-ui.com/themes/playground#dropdown-menu

**Comment by fbwoolf** [comment] 2023-10-03 17:27
I believe we want a dropdown, but it is labeled in Figma as a select?

EDIT: I almost feel like the settings menu is a `DropdownMenu` and the swap select is a `Select`?

From their docs:
Select => `Displays a list of options for the user to pick from—triggered by a button.`
DropdownMenu => `Displays a menu to the user—such as a set of actions or functions—triggered by a button.`

I think these are two different UI components to make?

**Comment by fbwoolf** [comment] 2023-10-03 18:05
Also a bit confused here on the file location, we currently have a `components` folder, is that what you mean in description? Or, should I start a new folder singular? Maybe we want something completely separate, like `ui` so those can be pulled out to share if needed later?

`@app/ui/components/dropdown-menu`?

**Comment by fbwoolf** [comment] 2023-10-03 18:10
Guess Select has a position prop...

<img width="1269" alt="Screen Shot 2023-10-03 at 1 09 45 PM" src="https://github.com/leather-wallet/extension/assets/6493321/ef1366db-88f6-480e-8f2e-f59d8b6eb0f1">

**Comment by pete-watters** [comment] 2023-10-04 07:49
> https://www.radix-ui.com/themes/playground#select

This is what I was thinking too @fbwoolf . They are really two different components. The radix `select` component looks good for more basic types of select but I think we want to have more complexly styled rows so we want to create a dropdown that we can use as both a dropdown menu and custom `select`

What we can do is have a dropdown component for both of them but with different triggers
- for the `Settings` menu, the trigger is a button
- for the `Select` the trigger is a button that is styled to look like a select option

Inside of the menu itself we would then have child components for each row like 
- asset row
- receive row
- settings menu row

Doing things that way and we can share a lot of code between UI implementations and also do more cool stuff in the select like hot keys etc. 

So it would be like this:

```
// @app/ui/components/menu 
<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    <!--  Icon button for Settings menu -->
    <!--  Full width button for Select menu - like we have in swaps--> 
  </DropdownMenu.Trigger>
  <DropdownMenu.Content>
    <DropdownMenu.Item shortcut="⌘ E">Some settings menu item</DropdownMenu.Item>
    <DropdownMenu.Separator />
    <DropdownMenu.Item shortcut="⌘ N">
     {assets.map(asset => <AssetRow variant='receive' asset={asset} >)}
     </DropdownMenu.Item>
</DropdownMenu.Root>
```

I don't mind what we call it but I think it is a good idea to put it in a subfolder like `@app/ui/` or `@app/components/ui/`. Then we can start adding all our bespoke `radix` components there. 

We can even have wrapper components for the two variants then so we would have:
- `@app/ui/components/menu` - base bespoke `radix` dropdown
- `@app/ui/components/select ` - imports and builds on `menu` to make it behave more like a select - for swaps etc.
- `@app/ui/components/dropdown ` - imports and builds on `menu` to make it behave more like a dropdown - for select menu

We may even be over-thinking this a bit. I know of only one place where we need the `dropdown-menu` - for settings. We may use the `select` in more places - for `swap`, `send` etc.

**Comment by fbwoolf** [comment] 2023-10-04 15:27
@pete-watters thanks for the reply. It appears we are on the same page here. 👍

**Comment by fbwoolf** [comment] 2023-12-20 16:55
I feel like this issue is a duplicate of newer issues so I'm going to close it and start those instead.

**Closed as completed by fbwoolf** 2023-12-20 16:55 UTC
Labels: area:ui
