### ISSUE TITLE
Stacks logo and balance not loading in the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5466] opened 2024-05-29 19:51 UTC
A user found his Stacks balances not loading. In fact "Stacks" is not even shown which is unexpected, because it should show with a loading state or 0 balance. Nothing at all is unexpected. 

The user has additional tokens in the wallet. Acct1 has STX, DIKO, ALEX, and WELSH (no BTC).

![image](https://github.com/leather-wallet/extension/assets/33360391/76a23ca8-d5ee-48e7-ac94-66e899202388)

Link to dev-conversation about this: https://trustmachines.slack.com/archives/C05LAP952E7/p1716995618077349

**Comment by 314159265359879** [comment] 2024-05-29 19:56
design related thread: https://trustmachines.slack.com/archives/C05LRS7G44R/p1717005174975809

**Comment by pete-watters** [comment] 2024-05-30 04:56
@314159265359879 is this specifically an issue with Ledger? We are assuming that but it would be good to confirm and get precise details as we cannot reproduce it.

It seems like a similar problem to one we face here: https://github.com/leather-wallet/extension/issues/4787

**Comment by 314159265359879** [comment] 2024-05-30 06:25
I don't think the user is using a hardware device, but I am checking this with them to make sure. 

They just reported that after restarting their Mac, Leather is loading their assets normally.

**Comment by pete-watters** [comment] 2024-05-30 08:18
> I don't think the user is using a hardware device, but I am checking this with them to make sure.
> 
> They just reported that after restarting their Mac, Leather is loading their assets normally.

OK thanks. Asking as you had said the `Connect Stacks` button didn't show but that should only ever show up for a hardware wallet.

**Comment by 314159265359879** [comment] 2024-05-31 07:18
@pete-watters, I'm sorry for the confusion. I meant it as a hypothetical. "If they had had Stacks connected, I would have expected to see that button."

The user confirmed they were using Leather in software mode when they encountered this error.

**Comment by pete-watters** [comment] 2024-05-31 08:59
> @pete-watters, I'm sorry for the confusion. I meant it as a hypothetical. "If they had had Stacks connected, I would have expected to see that button."
> 
> The user confirmed they were using Leather in software mode when they encountered this error.

No problem, thanks! It seems like the team understood right away anyway and already have a fix in flight 😄

**Comment by markmhendrickson** [comment] 2024-06-05 14:28
Component design needs two new states:

1. Simple server-side loading error with no retry option
2. Error _with_ retry option (e.g. for 429s)

**Comment by mica000** [comment] 2024-06-05 18:54
> Component design needs two new states:
> 
> 1. Simple server-side loading error with no retry option
> 2. Error _with_ retry option (e.g. for 429s)

@markmhendrickson Looks like this comment and the asignment belongs to another [ticket](https://github.com/leather-wallet/extension/pull/5467#event-13052386153)

**Comment by markmhendrickson** [comment] 2024-06-06 05:04
This is the issue resolved by the PR you link.

**Closed as completed** 2024-06-17 16:25 UTC
Labels: bug, bug-p2, area:api
