### ISSUE TITLE
Application error when sending certain SIP10 tokens

### ISSUE THREAD

**Issue by DeeList** [blockstack/blockstack-app#5436] opened 2024-05-24 01:41 UTC
The error occurs in 6.41.0 when trying to send certain tokens. I could only see the issue when testing the send of these tokens NOT, BULL, MOJO, FOX, DOGE, ALL.

<img width="296" alt="siperror" src="https://github.com/leather-wallet/extension/assets/132958967/118c4695-cf04-4a8d-9756-f55b105ced7c">

**Comment by pete-watters** [comment] 2024-05-24 05:05
I checked this with DOGE and can reproduce.

It's failing as we have some code that is looking for an entry for a 3rd item in the `tx.payload.functionArgs[3]` .

I'm not familiar with this flow so not sure why its hardcoded to look for `functionArgs[3]` . Looking at related code it could be the memo should be there? I tried sending with a memo and no luck.

I checked and the change comes from this PR: https://github.com/leather-wallet/extension/pull/4696 

We had an open Q about it: https://github.com/leather-wallet/extension/pull/4696#discussion_r1426503504

**Comment by pete-watters** [comment] 2024-05-24 05:25
I have added some defensive code that will stop the UI crashing and allow users to get past the initial error but when I try and actually send these tokens it fails at the next step:
![Screenshot 2024-05-24 at 06 21 43](https://github.com/leather-wallet/extension/assets/2938440/b02cd9ef-a01e-4f3f-b61c-b8bffd7bba03)

It gives a `400 (Bad Request)` from https://api.hiro.so/v2/transactions then a transaction broadcast error: 
```
{
    "error": "transaction rejected",
    "reason": "BadFunctionArgument",
    "reason_data": {
        "message": "IncorrectArgumentCount(4, 3)"
    },
    "txid": "33903b1126f0dea7234a58ec879f00cc1d38c844d26837024b01d76ace168cef"
}
```

It seems like these tokens are missing the 4th entry in `functionArgs` (`functionArgs[3]`) which is needed

**Comment by 314159265359879** [comment] 2024-05-24 07:31
I tested 6.41.0 with several SIP010 tokens but not these; I am surprised there is a difference between them, though.

**Comment by pete-watters** [comment] 2024-05-24 08:35
I merged am improvement https://github.com/leather-wallet/extension/pull/5438 so that we don't crash the UI on send here but broadcast is still failing

**Comment by kyranjamie** [comment] 2024-05-24 08:38
Yeah so 4 arguments are indeed required, not sure where/how this changed.

[`(transfer ((amount uint) (sender principal) (recipient principal) (memo (optional (buff 34)))) (response bool uint))`](https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md#:~:text=(transfer%20((amount%20uint)%20(sender%20principal)%20(recipient%20principal)%20(memo%20(optional%20(buff%2034))))%20(response%20bool%20uint)))

Looks like `useGenerateFtTokenTransferUnsignedTx` has changed recently with some refactor work so likely introduced there. 

Does this code not run? 

https://github.com/leather-wallet/extension/blob/cd0dc590ab9866a5634e577a3695733447e185df/src/app/store/transactions/token-transfer.hooks.ts#L126-L128

**Comment by pete-watters** [comment] 2024-05-24 09:22
> Yeah so 4 arguments are indeed required, not sure where/how this changed.
> 
> [`(transfer ((amount uint) (sender principal) (recipient principal) (memo (optional (buff 34)))) (response bool uint))`](https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md#:~:text=(transfer%20((amount%20uint)%20(sender%20principal)%20(recipient%20principal)%20(memo%20(optional%20(buff%2034))))%20(response%20bool%20uint)))
> 
> Looks like `useGenerateFtTokenTransferUnsignedTx` has changed recently with some refactor work so likely introduced there.
> 
> Does this code not run?
> 
> https://github.com/leather-wallet/extension/blob/cd0dc590ab9866a5634e577a3695733447e185df/src/app/store/transactions/token-transfer.hooks.ts#L126-L128

I checked and we don't seem to hit this section at all. I can look into it.

On retry a send of `DOGE` I got different errors. First it got rejected for a `BadNonce`: 
 ![Screenshot 2024-05-24 at 10 08 40](https://github.com/leather-wallet/extension/assets/2938440/420e0a24-c1b8-42b3-a69b-5ec047576ca3)

Then it got rejected for another issue, I assume relates to API rate limiting: 
```
Your transaction failed to broadcast because of the error: cannot read properties of undefined (reading 'startswith')
```

I notice that we also don't convert the amount from DOGE to USD and I can see a console error for a 404 to `https://api.coincap.io/v2/assets/undefined ` 

When tried to roll back to [v6.40.0](https://github.com/leather-wallet/extension/releases/tag/v6.40.0) to test as I think the bug could come from https://github.com/leather-wallet/extension/pull/5414 but I am getting a ton of API issues, rate limiting etc. in the `dev` wallet. I tried using a VPN but no luck.

I will keep investigating

**Comment by pete-watters** [comment] 2024-05-24 16:08
@DeeList @314159265359879 , we have a release for this ready: https://github.com/leather-wallet/extension/pull/5450 

Can you confirm that sending of these tokens was working previously? It's unclear if this is a regression or something that wasn't working in the past either. Any help QA-ing the release would be most appreciated. Thanks!

CC @fbwoolf

**Comment by fbwoolf** [comment] 2024-05-24 16:31
Will close this again bc it was released.

**Closed as completed by fbwoolf** 2024-05-24 16:31 UTC
Labels: bug-p1
