### ISSUE TITLE
Unable to sign messages on Ledger for particular actions. 

### ISSUE THREAD

**Issue by ttiiggss** [blockstack/blockstack-app#2844] opened 2022-11-12 02:53 UTC
Hi! And thank you for reading!

Having some issues with signing into some sites on my Ledger using Hiro. Some actions seem to work, others don't. 

Am able to sign into gamma.io, can purchase items, 
- however -
I *cannot* edit my profile or sign the message hash with many sites. These include Console and many other web3 sites. A hot wallet version works but using my Ledger sadly leaves me in the cold to call it functioning.

This is the main error I get and it replicates when I use my Nano S as well as my Nano S+. Both updated to the latest firmware and software versions from ledger live. 

![brave_B2oHIP2xUB](https://user-images.githubusercontent.com/30672576/201453265-b6c9925f-02e8-40fa-a9e7-5abd17a2a332.png)

**Comment by 314159265359879** [comment] 2022-11-13 16:38
Awesome you also made a ticket here. We expect this to get resolved with the resolution to this issue here: https://github.com/hirosystems/stacks-wallet-web/issues/2725

The fix is built but it takes some more time for Ledger to accept. The fix is for the Stacks app for Ledger Live, as soon as you get version 0.23.4 we expect this to be resolved. We'd love to hear from users after they get the new release. 

You already know this but I thought this could be good to know for anyone else finding this.

**Comment by 314159265359879** [comment] 2022-11-16 13:58
Closing because it is a duplicate of #2725

**Closed as completed by 314159265359879** 2022-11-16 13:58 UTC
Labels: bug
