### ISSUE TITLE
Show memo in activity for transactions

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2871] opened 2022-11-17 12:32 UTC
For both inbound and outbound transactions. Right now it's just blank

[Per request on Twitter](https://twitter.com/nattaja_btc/status/1592936457001656320)

**Comment by 314159265359879** [comment] 2024-06-04 09:03
Dupe of https://github.com/leather-wallet/extension/issues/2695 closing this in favor of the other one.

**Closed as completed by 314159265359879** 2024-06-04 09:03 UTC
Labels: good-first-issue, enhancement-p2, area:send, enhancement
