### ISSUE TITLE
Prevent animated fade to dark mode every time wallet is loading into new window

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3361] opened 2023-03-05 12:13 UTC
Window should appear from the start in dark mode, not transition from light each time

https://user-images.githubusercontent.com/28991/222959793-de0d2480-67f0-48fb-83ec-fa8025ce2828.mov

**Comment by kyranjamie** [comment] 2023-03-05 19:33
Dupe of #3314

**Closed as completed** 2023-03-21 14:56 UTC
